[common]
items = [100, 1000, 5000, 10000, 15000, 20000, 30000]

[[profiles]]
name = "minimum"
producers = 1
consumers = 1

[[profiles]]
name = "medium"
producers = 5
consumers = 1

[[profiles]]
name = "heavy"
producers = 20
consumers = 2

[[profiles]]
name = "producers"
producers = 2
consumers = 0

[[profiles]]
name = "consumers"
producers = 0
consumers = 2
